### ISSUE TITLE
[Bug] Buttons on index page not working 

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/QuickQuiz#42]
https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/121642923/19fefe95-60df-42b5-87f0-5ad045da6b55

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by Akanchha112** [comment]
> Kviz_.A.quiz.app.-.Google.Chrome.2024-01-03.03-44-35.mp4

Hey @priyagupta20044, I think, after cloning the repository you didn't go to the QuickQuiz folder, that's why you are facing this issue. Here are the steps you have to follow:
1. Clone the repository in a folder
2. After cloning close VS code
3. Go to the QuickQuiz folder 
4. Open it in VScode
5. Run index.html file
After following these steps, you can successfully use the whole project without any errors.
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/100962900/8c47470e-ca2e-43c2-aada-2507adac5e36)
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/100962900/fa4a0912-2e82-471d-8908-f6bd60991a33)

**Comment by Nitya-Pasrija** [comment]
Closing this issue, as it was has been clarified :)
